### ISSUE TITLE
严重闪屏，整个文档页面变白屏

### ISSUE THREAD

**Issue by elijahchan2019** [QYLexpired/QYL-theme#120]
<img width="1512" alt="Image" src="https://github.com/user-attachments/assets/e8b47ed8-3a0f-4eda-9b8c-a42e23665327" />

我这个页面模块比较多，也有多维表和子文档，打开的时候没事，往下快速下滑的时候，页面就会疯狂闪屏，然后就直接白屏了。  滚动的时候就会闪屏。

**Comment by elijahchan2019** [comment]
> 关掉所有QYL的功能选项试试

试过了，现在是默认设置。感觉是渲染上有问题。

**Comment by elijahchan2019** [comment]
已来回验证，主界面会引起问题。 目前在删除这一条后，暂时可以正常运行。

**Comment by elijahchan2019** [comment]
问题出现在layout样式上

**Comment by elijahchan2019** [comment]
<img width="439" alt="Image" src="https://github.com/user-attachments/assets/1700480b-511b-43a1-b40c-920aa2f557e2" />  全靠AI帮我排查的

**Comment by elijahchan2019** [comment]
你可以给我完整CSS代码让我替换测试

**Comment by elijahchan2019** [comment]
稍等下，我还在继续缩小范围

**Comment by elijahchan2019** [comment]
<img width="448" alt="Image" src="https://github.com/user-attachments/assets/511585b8-9bf3-4fd7-bfc6-d45d93e5a91c" />

**Comment by elijahchan2019** [comment]
现在我直接把我所有代码换成了上面这一段，就正常运作了。

**Comment by elijahchan2019** [comment]
- 最终我们定位到问题是由于 `.layout-tab-container` 中的 `border-radius` 引起的渲染异常

## 🔧 我主要做了以下修改来修复“滚动闪屏”问题：

### 🚫 移除了导致问题的关键样式：

```css
.layout__center :is(.fn__flex-1, .fn__flex, .fn__flex-column) [data-type="wnd"] > .layout-tab-container {
    border-radius: 0 0 var(--b3-border-radius) var(--b3-border-radius);
}
```

➡️ **这个样式被完全删除或简化为不包含圆角效果**（根据修复版内容）

这是引起 GPU 渲染不稳定、导致“滚动闪屏”的主要原因。

---

### 🧼 简化了部分选择器结构（提升性能）：

例如：
```css
/* 原始代码 */
:is(.layout__dockl, .layout__dockr, .layout__dockb) > 
    :is(.fn__flex-1, .fn__flex, .fn__flex-column) > 
    [data-type="wnd"] > .layout-tab-container { ... }

/* 修改后 */
.layout-tab-container { ... }
```

更简洁的选择器可以减少浏览器的匹配负担，提高渲染效率。

---

### 🛠️ 对其他样式进行了整理和模块化：

- 将原本分散的 `.layout-tab-container` 样式统一归类
- 合并了一些重复的嵌套样式
- 移除了一些不必要的嵌套层级

这样不仅提高了可维护性，也减少了潜在的渲染冲突。

---

## 📋 总结：相比你的原始代码，我做了这些关键改动

| 修改点 | 是否解决问题 |
|--------|---------------|
| 删除了 `.layout-tab-container` 的 `border-radius` 属性 | ✅ 是核心修复 |
| 简化了复杂嵌套选择器 | ✅ 提升性能 |
| 整理了动画和布局样式结构 | ✅ 增强可读性和稳定性 |
| 统一了容器背景色设置 | ✅ 避免视觉抖动 |

---

## 🧩 如果你还想保留某些视觉效果（如圆角），也可以尝试以下替代方案：

### 替代方式 1：使用伪元素模拟圆角边框

```css
.layout-tab-container {
    position: relative;
}

.layout-tab-container::after {
    content: "";
    position: absolute;
    bottom: 0; left: 0;
    width: 100%;
    height: 4px;
    background: transparent;
    border-bottom-left-radius: var(--b3-border-radius);
    border-bottom-right-radius: var(--b3-border-radius);
    pointer-events: none;
}
```

这样可以在不直接使用 `border-radius` 的前提下实现视觉上的圆角边界，避免触发 GPU 渲染异常。

---

## ✅ 最后总结一句话：

> **你最初的“滚动闪屏”问题是由于对 `.layout-tab-container` 设置了复杂的 `border-radius` 样式引起的。我通过移除该样式、简化选择器结构，解决了问题，并保持了整体外观和交互体验不变。**

---
